### PR TITLE
support build for scala 2.13.0-M5

### PR DESCRIPTION
**Pull request by erikerlandson**
addresses #31

### CODE REVIEW

**Comment by erikerlandson** [comment]
CI is failing on scala native (2.11.12). Unsure why, although doesn't look related to any changes in this PR

**Comment by erikerlandson** [comment]
cc @xuwei-k

**Comment by xuwei-k** [comment]
https://github.com/typelevel/machinist/pull/33

**Comment by erikerlandson** [comment]
I'll rebase when #33 merges

**Comment by erikerlandson** [comment]
cc @non

**Comment by larsrh** [comment]
#33 is merged. @erikerlandson I've rebased for you. When the build is green, I'll run the release.

**Comment by erikerlandson** [comment]
thanks @larsrh !

**Pull request merged**
