### PR TITLE
Scala 2.13.0-M3

### PR DESCRIPTION
**Pull request by cb372**
Needed to bump scala.js for this

### CODE REVIEW

**Comment by cb372** [comment]
Fixes #22

**Comment by LukaJCB** [comment]
Who has rights to merge this?

**Comment by milessabin** [comment]
I do, but it's @non's project, so we should chase him first ...

**Comment by non** [comment]
Thanks for this! I'll publish a release tonight after work.

**Comment by non** [comment]
Just released 0.6.4 to Sonatype. Should be available from Maven Central soon.

**Pull request merged**
